dayfresh/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('df_user.urls',namespace='user')),
    url(r'^cart/',include('df_cart.urls',namespace='cart')),
    url(r'^goods/',include('df_goods.urls',namespace='goods')),
    url(r'^order/',include('df_order.urls'),name='order'),
    url(r'^',include('df_goods.urls'),name='goods'),
]

df_cart/urls.py
from django.conf.urls import url

from df_cart import views

urlpatterns = [
    url(r'^$',views.cart,name='cart' ),
    url(r'^delete/$',views.delete,name='delete'),
    url(r'^edit/$',views.edit,name='edit'),
    url(r'^add/$',views.add,name='add'),
]

df_user/urls.py
from django.conf.urls import url

from df_user import views

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^register_handle/$',views.register_handle,name='register_handle'),
    url(r'^register_exist/$',views.register_exist,name='register_exist'),
    url(r'^login/$',views.login,name='login'),
    url(r'^login_handle/$',views.login_handle,name='login_handle'),
    url(r'^info/$',views.info,name='info'),
    url(r'^order/$',views.order,name='order'),
    url(r'^site/$',views.site,name='site'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^user_center_order&(\d+)/$',views.user_center_order,name='user_center_order'),
]

df_order/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class OrderInfo(models.Model):
    oid=models.CharField(max_length=20,primary_key=True)
    user=models.ForeignKey('df_user.UserInfo')
    odate=models.DateTimeField(auto_now=True)
    oIsPay=models.IntegerField(default=0)
    ototal=models.DecimalField(max_digits=5,decimal_places=2)
    oaddress=models.CharField(max_length=150,default='')
    zhifu=models.IntegerField(default=0)

class OrderDetailInfo(models.Model):
    goods=models.ForeignKey('df_goods.GoodsInfo')
    order=models.ForeignKey(OrderInfo)
    price=models.DecimalField(max_digits=5,decimal_places=2)
    count=models.IntegerField()

df_user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class UserInfo(models.Model):
    uname=models.CharField(max_length=20)
    upwd=models.CharField(max_length=40)
    uemail=models.CharField(max_length=30)
    ushou=models.CharField(max_length=20,default='')
    uaddress=models.CharField(max_length=100,default='')
    ucode=models.CharField(max_length=6,default='')
    uphone=models.CharField(max_length=13,default='')

df_user/views.py
# -*- coding: utf-8 -*-
from django.core.paginator import Paginator
from django.http import JsonResponse,HttpResponse
from django.shortcuts import render,redirect,HttpResponseRedirect

from df_goods.models import GoodsInfo
from df_order.models import OrderInfo
from models import *
from hashlib import sha1
from .islogin import islogin



def register(request):
    return render(request,'df_user/register.html')

def register_handle(request):
    # 接受用户输入
    post=request.POST
    uname=post.get('user_name')
    upwd=post.get('pwd')
    upwd2=post.get('cpwd')
    uemail=post.get('email')
    # 判断两次密码输入是否一致
    if upwd!=upwd2:
        return redirect('/user/register/')
    # 加密
    s1=sha1()
    s1.update(upwd)
    upwd3=s1.hexdigest()
    # 创建对象
    user=UserInfo()
    user.uname=uname
    user.upwd=upwd3
    user.uemail=uemail
    user.save()
    # 注册成功，转到登陆页面
    return redirect('/user/login/')

def register_exist(request):
    uname=request.GET.get('uname')
    count=UserInfo.objects.filter(uname=uname).count()
    return JsonResponse({'count':count})

def login(request):
    uname=request.COOKIES.get('uname','')
    context={'title':'用户登录','error_name':0,'error_pwd':0,'uname':uname}
    return render(request,'df_user/login.html',context)

def login_handle(request):
    # 接受请求信息
    post=request.POST
    uname=post.get('username')
    upwd=post.get('pwd')
    jizhu=post.get('jizhu',0)
    # 根据用户名查询对象
    users=UserInfo.objects.filter(uname=uname)
    print uname
    # 判断：如果未查到则用户名错，如果查到则判断密码是否正确，正确则转到用户中心
    if len(users)==1:
        s1=sha1()
        s1.update(upwd)
        if s1.hexdigest()==users[0].upwd:
            red=HttpResponseRedirect('/user/info')
            # 记住用户名
            if jizhu!=0:
                red.set_cookie('uname',uname)
            else:
                red.set_cookie('uanem','',max_age=-1)
            request.session['user_id']=users[0].id
            request.session['user_name']=uname
            return red
        else:
            context={'title':'用户登录','error_name':0,'error_pwd':1,'uname':uname}
            return render(request,'df_user/login.html',context)
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname}
        return render(request, 'df_user/login.html', context)
# 用户退出
def logout(request):
    request.session.flush()
    return redirect('/')
# 登陆用户中心
@islogin
def info(request):
    user_email=UserInfo.objects.get(id=request.session['user_id']).uemail
    # 最近浏览记录
    goods_ids=request.COOKIES.get('goods_ids','')
    goods_id_list=goods_ids.split(',')
    goods_list=[]
    if len(goods_ids):
        for goods_id in goods_id_list:
            goods_list.append(GoodsInfo.objects.get(id=int(goods_id)))

    context={'title':'用户中心',
             'user_email':user_email,
             'user_name':request.session['user_name'],
             'page':1,
             'info':1,
             'goods_list':goods_list}
    return render(request,'df_user/user_center_info.html',context)
# 订单
@islogin
def order(request):
    context={'title':'用户中心','page_name':1,'order':1}
    return render(request,'df_user/user_center_order.html',context)
# 收获地址
@islogin
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method=='POST':
        post=request.POST
        user.ushou=post.get('ushou')
        user.uaddress=post.get('uaddress')
        user.uphone=post.get('uphone')
        user.ucode=post.get('ucode')
        user.save()
    context={'title':'用户中心','user':user,'page_name':1,'site':1}
    return render(request,'df_user/user_center_site.html',context)

# 此页面用户展示用户提交的订单，由购物车页面下单后转调过来，也可以从个人信息页面查看
# 根据用户订单是否支付、下单顺序进行排序

def user_center_order(request,pageid):
    uid=request.session.get('user_id')
    orderinfos=OrderInfo.objects.filter(user_id=uid).order_by('zhifu','-oid')
    # 分页
    paginator=Paginator(orderinfos,2)

    orderlist=paginator.page(int(pageid))

    plist=paginator.page_range
    # 3页分页显示
    qian1=0
    hou=0
    hou2=0
    qian2=0
    dd=int(pageid)
    lenn=len(plist)

    if dd>1:
        qian1=dd-1
    if dd>3:
        qian2=dd-2
    if dd<lenn:
        hou=dd+1
    if dd+2<lenn:
        hou2=dd+2
    context={'page_name':1,'title':'全部订单','pageid':int(pageid),'order':1,'orderlist':orderlist,
             'plist':plist,'pre':qian1,'next':hou,'pree':qian2,'lenn':lenn,'nextt':hou2}
    return render(request,'df_user/user_center_order.html',context)

templates/df_user/base.html
{% extends 'base.html' %}
{% block body %}
<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="/user/info" {% if info %} class="active" {% endif %}>· 个人信息</a></li>
            <li><a href="/user/user_center_order&1/" {% if order %} class="active" {% endif %}>· 全部订单</a></li>
            <li><a href="/user/site" {% if site %} class="active" {% endif %}>· 收货地址</a></li>
        </ul>
    </div>
    {% block right_content%}
    {% endblock right_content %}
</div>
{% endblock body %}

templates/df_user/login.html
{% extends 'base_foot.html' %}

{% block head %}
    <script>
    $(function () {
        name_error=false;
        pwd_error=false;
        if($('.name_input').val().length!=0){
            name_error = true
        }
        if($('.pwd_error').val().length!=0){
            pwd_error = true
        }

        if ({{error_name}}==1){
            $('.user_error').html('用户名错误').show();
        }
        if ({{error_pwd}}==1){
            $('.pwd_error').html('密码错误').show();
        }
        $('.name_input').blur(function () {
            if ($('.name_input').val().length==0){
                $('.user_error').html('请填写用户名').show();
                name_error=false
            }else {
                $('.user_error').hide();
                name_error=true;
            }
        })
        $('.pass_input').blur(function () {
            if ($(this).val().length==0){
                $('.pass_input').html('请输入密码').show();
                pwd_error=false
            }else {
                $('.pwd_error').hide();
                pwd_error=true
            }
        });
        $(":submit[id=lo]").click(function (check) {
            console.log(pwd_error,name_error)
        if (pwd_error==false||name_error==false){
             check.preventDefault();//阻止提交表单
        }
        });
    })
    </script>
{% endblock head %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle/" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ uname }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{ upwd }}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

templates/df_user/register.html
{% extends 'base_foot.html' %}
{% load static from staticfiles %}
{% block head %}
    <script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock head %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" id="reg_form" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'df_user/base.html' %}

{% block right_content %}
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <ul class="user_info_list">
                <li><span>用户名：</span>{{ user_name }}</li>
                <li><span>联系方式：</span>{{ user_email }}</li>
                <li><span>联系地址：</span>北京市昌平区</li>
            </ul>
        </div>
				
        <h3 class="common_title2">最近浏览</h3>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                {% for goods in goods_list %}
                <li>
					<a href="/{{ goods.id }}"><img src="/static/{{ goods.gpic }}"></a>
					<h4><a href="detail.html">{{ goods.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">{{ goods.gprice }}</span>
						<span class="unit">{{ goods.gprice }}/{{ goods.gunit}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
		</div>
		</div>
	</div>
{% endblock right_content %}

templates/df_user/user_center_order.html
{% extends 'df_user/base.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for orderinfo in orderlist %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{orderinfo.odate  }}</li>
					<li class="col02">订单号：{{ orderinfo.oid }}</li>
                    {% if orderinfo.zhifu == 1 %}
                    <li class="col02 stress">已支付</li>
                    {% else %}
					<li class="col02 stress">未支付</li>
                    {% endif %}
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                            {% for item in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/static/{{ item.goods.gpic }}"></li>
									<li class="col02">{{ item.goods.gtitle }}<em><span>{{ item.price }}</span>元/{{ item.goods.gunit }}</em></li>
									<li class="col03">{{ item.count }}个</li>
									<li class="col04"></li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ orderinfo.ototal }}</td>
                            {% if orderinfo.zhifu == 1 %}
							<td width="15%">已付款</td>
                            <td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                            {% else %}
							<td width="15%"><a href="#" class="oper_btn">未付款</a></td>
                            <td width="15%"><a href="/order/pay&{{ orderinfo.oid }}/" class="oper_btn">去付款</a></td>
                            {% endif %}
						</tr>
					</tbody>
				</table>
				{% endfor %}
                <div class="pagenation">
                    {% if orderlist.has_previous %}
                    <a href="/user/user_center_order&{{ orderlist.previous_page_number }}/">上一页</a>
                    {% endif %}
                    {% if lenn < 4 %}
                        {% if lenn == 1 %}
                        <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                        {% elif lenn == 2 %}
                            {% if pageid == 1 %}
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            <a href="/user/user_center_order&{{ next }}/">{{ next }}</a>
                            {% else %}
                            <a href="/user/user_center_order&{{ pre }}/">{{ pre }}</a>
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            {% endif %}
                        {% elif lenn == 3 %}
                            {% if pageid == 1%}
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            <a href="/user/user_center_order&{{ next }}/">{{ next }}</a>
                            <a href="/user/user_center_order&{{ nextt }}/">{{ nextt }}</a>
                            {% elif pageid == 2 %}
                            <a href="/user/user_center_order&{{ pre }}/">{{ pre }}</a>
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            <a href="/user/user_center_order&{{ next }}/">{{ next }}</a>
                            {% else %}
                            <a href="/user/user_center_order&{{ pree }}/">{{ pree }}</a>
                            <a href="/user/user_center_order&{{ pre }}/">{{ pre }}</a>
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            {% endif %}
                        {% endif %}
                    {% elif pageid < lenn %}
                        {% if orderlist.has_previous %}
                            <a href="/user/user_center_order&{{ pre }}/">{{ pre }}</a>
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            <a href="/user/user_center_order&{{ next }}/">{{ next }}</a>
                        {% else %}
                            <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                            <a href="/user/user_center_order&{{ next }}/">{{ next }}</a>
                            <a href="/user/user_center_order&{{ nextt }}/">{{ nextt }}</a>
                        {% endif %}
                    {% else %}
                        <a href="/user/user_center_order&{{ pree }}/">{{ pree }}</a>
                        <a href="/user/user_center_order&{{ pre }}/">{{ pre }}</a>
                        <a href="/user/user_center_order&{{ pageid }}/" class="active">{{ pageid }}</a>
                    {% endif %}
                {% if orderlist.has_next %}
                    <a href="/user/user_center_order&{{ orderlist.next_page_number }}/">下一页</a>
                {% endif %}
                </div>
		</div>
{% endblock right_content %}

templates/df_user/user_center_site.html
{% extends 'df_user/base.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }} ({{ user.uname }} 收) 电话：{{ user.uphone }} 邮编：{{ user.ucode }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="ucode" value="{{ user.ucode }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ user.uphone }}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock right_content %}